apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      role: application1
  template:
    metadata:
      labels:
        role: application1
    spec:
      restartPolicy: Always
      nodeName: node1
      containers:
        - name: container-1
          image: lerndevops/sampleapp:23
          ports:
            - name: http
              containerPort: 8080