apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: multi-container
spec:
  containers:
  - name: webserver1
    image: nginx:1.10-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: application-server
    image: alpine:3.5
    command: ["watch","wget","-qO-", "localhost"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"