kind: Service
apiVersion: v1
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  type: NodePort
  selector:
    app: example-pod
  ports:
  - port: 80
    targetPort: 4000
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-1
  labels:
    app: replica-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-1
    spec:
      containers:
        - name: container-1
          image: zlabjp/docker-example:release-0.1.0
          ports:
            - containerPort: 4000        