apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    name: single-container
spec:
  containers:
  - name: webserver1
    image: nginx:1.10-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80